---
- name: import repository key
  apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present
  become: true
- name: install chrome repository
  apt_repository:
    repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    filename: 'google-chrome'
    state: present
  become: true
- name: install chrome package
  apt:
    name: google-chrome-stable
    state: present
  become: true
