---
- apt_key: url=https://dl.google.com/linux/linux_signing_key.pub state=present
  sudo: yes
- apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present
  sudo: yes
- apt: name=google-chrome-stable state=present
  sudo: yes


