---
- apt: name={{ item }} state=present
  with_items:
  - lxde-core
  - lxde-icon-theme
  - xfce4-terminal
  - fonts-inconsolata
  - fonts-powerline
  - xrdp
  become: yes
- alternatives: name=x-session-manager path=/usr/bin/startlxde
  become: yes
