---
- hosts: localhost
  remote_user: ubuntu
  tasks:
    - set_fact: inadyn="{{ lookup('aws_ssm', '/alsl-ec2-dev/roles/inadyn', shortnames=true, bypath=true, recursive=true, decrypt=true) }}"
- import_playbook: ../ansible/devenv.yml
