---
- apt_key: keyserver=keyserver.ubuntu.com id=EA312927 state=present
  sudo: yes
- apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present
  sudo: yes
- apt: name=mongodb-org state=present
  sudo: yes


