---
- apt_key: url=https://packages.microsoft.com/keys/microsoft.asc state=present
  become: yes
- apt_repository: repo='https://packages.microsoft.com/repos/vscode stable main' filename='vscode' state=present
  become: yes
- apt: name=code state=present
  become: yes


